parameters:
    database_driver: pdo_pgsql
    database_host: localhost
    database_port: '5432'
    database_name: symblog
    database_user: postgres
    database_password: postgres
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ba47e1bbeb367f8b9a919138961f61066
    database_path: null
